// pages/account/profile.vue
<script setup lang="ts">
import { computed, onMounted, ref } from 'vue'

interface AuthSessionResponse {
  authenticated: boolean
  user?: { id: string; displayContact: string }
  authMethod?: 'otp' | 'passkey' | 'unknown'
  recentOtpAuthenticated?: boolean
  passkeys?: {
    passkeysEnabled: boolean
    passkeysConfigured: boolean
  }
}

interface UserCompany {
  id: string
  name: string
  nif: string
  role: 'admin' | 'member'
  active: boolean
}

interface ProfileResponse {
  authenticated: boolean
  user?: { id: string; displayContact: string }
  verifiedEmails: string[]
  companies: UserCompany[]
  activeCompany: UserCompany | null
}

const profile = ref<ProfileResponse>({ authenticated: false, verifiedEmails: [], companies: [], activeCompany: null })
const authSession = ref<AuthSessionResponse>({ authenticated: false })
const authPanelOpen = ref(false)
const selectedCompanyId = ref('')
const loading = ref(true)
const pending = ref(false)
const feedback = ref('')
const errorMessage = ref('')

const displayContact = computed(() => profile.value.user?.displayContact ?? '')
const userInitial = computed(() => displayContact.value.slice(0, 1).toUpperCase() || 'U')
const isEmailContact = computed(() => displayContact.value.includes('@'))
const planLabel = computed(() => {
  if (profile.value.activeCompany) return `Empresa — ${profile.value.activeCompany.name}`
  return 'Gratuito'
})
const verifiedContactList = computed(() => {
  if (profile.value.verifiedEmails.length > 0) return profile.value.verifiedEmails
  return displayContact.value ? [displayContact.value] : []
})

onMounted(() => {
  void loadProfile()
})

async function loadProfile(): Promise<void> {
  loading.value = true
  errorMessage.value = ''
  try {
    const response = await fetch('/api/account/profile')
    profile.value = response.ok
      ? ((await response.json()) as ProfileResponse)
      : { authenticated: false, verifiedEmails: [], companies: [], activeCompany: null }
    authSession.value = { authenticated: profile.value.authenticated, user: profile.value.user }
    selectedCompanyId.value = profile.value.activeCompany?.id ?? ''
  } catch {
    errorMessage.value = 'Não foi possível carregar o perfil.'
    authSession.value = { authenticated: false }
  } finally {
    loading.value = false
  }
}

async function saveActiveCompany(): Promise<void> {
  pending.value = true
  feedback.value = ''
  errorMessage.value = ''
  try {
    const response = await fetch('/api/account/active-company', {
      method: 'PUT',
      headers: { 'content-type': 'application/json' },
      body: JSON.stringify({ companyId: selectedCompanyId.value || null })
    })
    if (!response.ok) {
      errorMessage.value = 'Não foi possível seleccionar a empresa activa.'
      return
    }
    feedback.value = selectedCompanyId.value ? 'Empresa activa actualizada.' : 'Contexto individual seleccionado.'
    await loadProfile()
  } catch {
    errorMessage.value = 'Não foi possível seleccionar a empresa activa.'
  } finally {
    pending.value = false
  }
}

function handleAuthenticatedSession(session: AuthSessionResponse): void {
  authSession.value = session
  void loadProfile()
}
</script>

<template>
  <main v-if="loading" class="subpage" aria-labelledby="profile-title">
    <section class="adm-card"><p class="adm-sub">A carregar perfil...</p></section>
  </main>

  <main v-else-if="!profile.authenticated" class="subpage adm-gate" aria-labelledby="profile-title" data-screen-label="Perfil — sem sessão">
    <span class="adm-gate-icon"><UjimuIcon name="user" /></span>
    <h1 id="profile-title" class="subpage-title">O meu perfil</h1>
    <p class="subpage-sub" style="margin-top: 0">Inicie sessão para gerir o seu perfil.</p>
    <div class="adm-row-actions" style="justify-content: center">
      <NuxtLink class="btn btn--ghost" to="/">Voltar à consulta</NuxtLink>
      <button class="btn btn--primary" type="button" @click="authPanelOpen = true">Entrar por OTP</button>
    </div>
  </main>

  <main v-else class="subpage" aria-labelledby="profile-title" data-screen-label="Perfil">
    <NuxtLink class="btn btn--ghost btn--back" to="/"><UjimuIcon name="chevLeft" /> Voltar à consulta</NuxtLink>

    <div class="prof-head">
      <span class="avatar prof-avatar">{{ userInitial }}</span>
      <div>
        <h1 id="profile-title" class="subpage-title">O meu perfil</h1>
        <p class="subpage-sub">{{ displayContact }}</p>
      </div>
    </div>

    <div class="adm-card">
      <h2 class="adm-card-title">Dados pessoais</h2>
      <div class="adm-formgrid">
        <label class="adm-field">
          <span class="adm-field-label">Nome</span>
          <input class="field" value="" placeholder="O seu nome" readonly />
        </label>
        <label class="adm-field">
          <span class="adm-field-label">{{ isEmailContact ? 'Email' : 'Telemóvel' }}</span>
          <input class="field" :value="displayContact" readonly />
        </label>
      </div>
      <label class="adm-field">
        <span class="adm-field-label">{{ isEmailContact ? 'Telemóvel · opcional' : 'Email · opcional' }}</span>
        <input class="field" :type="isEmailContact ? 'tel' : 'email'" :placeholder="isEmailContact ? '9XX XXX XXX' : 'nome@exemplo.co.ao'" readonly />
      </label>
      <p class="adm-foot-note">Para alterar o contacto de entrada será pedido um código OTP enviado para o novo contacto. O contacto alternativo é opcional e pode ser usado para OTP.</p>
    </div>

    <div class="adm-card">
      <div class="adm-card-toprow">
        <div>
          <h2 class="adm-card-title">Subscrição</h2>
          <p class="adm-card-note">Plano actual: <strong>{{ planLabel }}</strong></p>
        </div>
        <NuxtLink class="btn btn--ghost btn--xs" to="/subscription">Gerir</NuxtLink>
      </div>
      <div v-if="profile.companies.length > 0" class="adm-srcs">
        <div v-for="company in profile.companies" :key="company.id" class="adm-src">
          <div class="adm-src-row">
            <div class="adm-src-meta">
              <span class="adm-src-name">{{ company.name }}</span>
              <span class="adm-src-sub">{{ company.role === 'admin' ? 'Administrador da Empresa · membro' : 'Membro' }}</span>
            </div>
            <span class="badge" :class="company.active ? 'badge--ok' : 'badge--mute'"><span class="badge-dot" />{{ company.active ? 'Activa' : 'Inactiva' }}</span>
          </div>
        </div>
      </div>
      <label v-if="profile.companies.length > 0" class="adm-field">
        <span class="adm-field-label">Empresa activa</span>
        <select v-model="selectedCompanyId" class="field" :disabled="pending">
          <option value="">Contexto individual</option>
          <option v-for="company in profile.companies" :key="company.id" :value="company.id">
            {{ company.name }} — {{ company.role === 'admin' ? 'admin' : 'membro' }}
          </option>
        </select>
      </label>
      <div v-if="profile.companies.length > 0" class="adm-row-actions">
        <button class="btn btn--primary btn--xs" type="button" :disabled="pending" @click="saveActiveCompany">Guardar empresa activa</button>
      </div>
      <p v-if="profile.companies.length > 1" class="adm-foot-note">Pertence a {{ profile.companies.length }} empresas — só uma pode estar activa de cada vez. Escolha a empresa activa no menu lateral.</p>
    </div>

    <div class="adm-card">
      <h2 class="adm-card-title">Segurança</h2>
      <div class="adm-srcs">
        <div class="adm-src">
          <div class="adm-src-row">
            <div class="adm-src-meta">
              <span class="adm-src-name">Entrada por código OTP</span>
              <span class="adm-src-sub">Cada início de sessão exige um código enviado por {{ isEmailContact ? 'email' : 'SMS' }}. Não há palavra-passe a memorizar.</span>
            </div>
            <span class="badge badge--ok"><span class="badge-dot" />Activo</span>
          </div>
        </div>
        <div class="adm-src">
          <div class="adm-src-row">
            <div class="adm-src-meta">
              <span class="adm-src-name">Contactos verificados</span>
              <span class="adm-src-sub">{{ verifiedContactList.join(' · ') }}</span>
            </div>
            <NuxtLink class="btn btn--ghost btn--xs" to="/account/security">Gerir passkeys</NuxtLink>
          </div>
        </div>
      </div>
    </div>

    <div class="adm-card adm-dangerzone">
      <div class="adm-card-toprow">
        <div>
          <h2 class="adm-card-title">Apagar conta</h2>
          <p class="adm-card-note">Apaga a conta e todo o histórico de conversas, permanentemente.</p>
        </div>
        <button class="btn btn--danger btn--xs" type="button" disabled>Apagar</button>
      </div>
    </div>

    <p v-if="feedback" class="plan-current--on"><UjimuIcon name="check" /> {{ feedback }}</p>
    <p v-if="errorMessage" class="adm-src-error" role="alert">{{ errorMessage }}</p>
  </main>

  <AuthModal v-model:open="authPanelOpen" :auth-session="authSession" @authenticated="handleAuthenticatedSession" />
</template>

<style scoped>
a.btn { text-decoration: none; }
</style>

// mock/ujimu/profile.jsx
// Ujimu — página de perfil do utilizador registado
const { useState: useProfState } = React;

function ProfilePage({ user, subscriber, company, memberships, activeCompanyId, onBack, onUpdateUser, onGoSubscription, onLogin, onLogout }) {
  const [name, setName] = useProfState(user ? (user.name || '') : '');
  const [phone, setPhone] = useProfState(user ? (user.phone || '') : '');
  const [saved, setSaved] = useProfState(false);
  const [confirmDel, setConfirmDel] = useProfState(false);

  if (!user) {
    return (
      <div className="subpage adm-gate" data-screen-label="Perfil — sem sessão">
        <span className="adm-gate-icon"><Icon name="user" size={26} /></span>
        <h1 className="subpage-title">O meu perfil</h1>
        <p className="subpage-sub" style={{ marginTop: 0 }}>Inicie sessão para gerir o seu perfil.</p>
        <div className="adm-row-actions" style={{ justifyContent: 'center' }}>
          <button className="btn btn--ghost" onClick={onBack}>Voltar à consulta</button>
          <button className="btn btn--primary" onClick={onLogin}>Entrar por OTP</button>
        </div>
      </div>
    );
  }

  const isEmail = user.contact.includes('@');
  const companyRole = company && company.accounts.find((a) => a.email === user.contact.toLowerCase());
  const ms = memberships || [];
  const activeM = ms.find((m) => m.id === activeCompanyId);
  const planLabel = company
    ? 'Empresa — ' + company.name + (companyRole && companyRole.role === 'admin' ? ' (administrador)' : ' (membro)')
    : ms.length > 0 ? 'Empresa — ' + (activeM ? activeM.name : 'sem empresa activa')
    : subscriber ? 'Subscritor individual' : 'Gratuito';

  function save() {
    onUpdateUser({ name: name.trim(), phone: phone.trim() });
    setSaved(true);
    setTimeout(() => setSaved(false), 2000);
  }

  return (
    <div className="subpage" data-screen-label="Perfil">
      <button className="btn btn--ghost btn--back" onClick={onBack}><Icon name="chevLeft" size={16} /> Voltar à consulta</button>
      <div className="prof-head">
        <span className="avatar prof-avatar">{user.initials}</span>
        <div>
          <h1 className="subpage-title" style={{ marginTop: 0 }}>{user.name || 'O meu perfil'}</h1>
          <p className="subpage-sub" style={{ marginTop: -4 }}>{user.contact}</p>
        </div>
      </div>

      <div className="adm-card">
        <h2 className="adm-card-title">Dados pessoais</h2>
        <div className="adm-formgrid">
          <label className="adm-field">
            <span className="adm-field-label">Nome</span>
            <input className="field" placeholder="O seu nome" value={name} onChange={(e) => setName(e.target.value)} />
          </label>
          <label className="adm-field">
            <span className="adm-field-label">{isEmail ? 'Email' : 'Telemóvel'}</span>
            <input className="field" value={user.contact} readOnly />
          </label>
        </div>
        <label className="adm-field">
          <span className="adm-field-label">{isEmail ? 'Telemóvel · opcional' : 'Email · opcional'}</span>
          <input className="field" type={isEmail ? 'tel' : 'email'} placeholder={isEmail ? '9XX XXX XXX' : 'nome@exemplo.co.ao'} value={phone} onChange={(e) => setPhone(e.target.value)} />
        </label>
        <div className="adm-row-actions">
          {saved && <span className="plan-current--on" style={{ fontSize: 12.5 }}><Icon name="check" size={13} /> Guardado</span>}
          <button className="btn btn--primary btn--xs" onClick={save}>Guardar alterações</button>
        </div>
        <p className="adm-foot-note">Para alterar o {isEmail ? 'email' : 'número'} de entrada será pedido um código OTP enviado para o novo contacto. O {isEmail ? 'telemóvel' : 'email'} é opcional e pode ser usado como contacto alternativo para OTP.</p>
      </div>

      <div className="adm-card">
        <div className="adm-card-toprow">
          <div>
            <h2 className="adm-card-title">Subscrição</h2>
            <p className="adm-card-note">Plano actual: <strong>{planLabel}</strong></p>
          </div>
          <button className="btn btn--ghost btn--xs" onClick={onGoSubscription}>Gerir</button>
        </div>
        {ms.length > 0 && (
          <div className="adm-srcs">
            {ms.map((m) => (
              <div className="adm-src" key={m.id}>
                <div className="adm-src-row">
                  <div className="adm-src-meta">
                    <span className="adm-src-name">{m.name}</span>
                    <span className="adm-src-sub">{m.role === 'admin' ? 'Administrador da Empresa · membro' : 'Membro'}</span>
                  </div>
                  {m.id === activeCompanyId
                    ? <span className="badge badge--ok"><span className="badge-dot"></span>Activa</span>
                    : <span className="badge badge--mute"><span className="badge-dot"></span>Inactiva</span>}
                </div>
              </div>
            ))}
          </div>
        )}
        {ms.length > 1 && <p className="adm-foot-note">Pertence a {ms.length} empresas — só uma pode estar activa de cada vez. Escolha a empresa activa no menu lateral.</p>}
      </div>

      <div className="adm-card">
        <h2 className="adm-card-title">Segurança</h2>
        <div className="adm-srcs">
          <div className="adm-src">
            <div className="adm-src-row">
              <div className="adm-src-meta">
                <span className="adm-src-name">Entrada por código OTP</span>
                <span className="adm-src-sub">Cada início de sessão exige um código enviado por {isEmail ? 'email' : 'SMS'}. Não há palavra-passe a memorizar.</span>
              </div>
              <span className="badge badge--ok"><span className="badge-dot"></span>Activo</span>
            </div>
          </div>
          <div className="adm-src">
            <div className="adm-src-row">
              <div className="adm-src-meta">
                <span className="adm-src-name">Sessões activas</span>
                <span className="adm-src-sub">Este dispositivo (Luanda, agora) · Chrome em Windows (há 2 dias)</span>
              </div>
              <button className="btn btn--ghost btn--xs" onClick={onLogout}>Terminar todas</button>
            </div>
          </div>
        </div>
      </div>

      <div className="adm-card adm-dangerzone">
        <div className="adm-card-toprow">
          <div>
            <h2 className="adm-card-title">Apagar conta</h2>
            <p className="adm-card-note">Apaga a conta e todo o histórico de conversas, permanentemente.</p>
          </div>
          <button className="btn btn--danger btn--xs" onClick={() => setConfirmDel(true)}>Apagar</button>
        </div>
      </div>

      {confirmDel && (
        <div className="modal-scrim" onClick={() => setConfirmDel(false)}>
          <div className="modal" role="dialog" aria-modal="true" onClick={(e) => e.stopPropagation()}>
            <div className="modal-body" style={{ paddingTop: 18, paddingBottom: 6 }}>
              <h2 className="modal-title">Apagar a sua conta?</h2>
              <p className="modal-sub">Todo o histórico de conversas será apagado permanentemente. {company ? 'A conta deixa de contar para os lugares da ' + company.name + '.' : ''}</p>
              <div className="adm-row-actions">
                <button className="btn btn--ghost" onClick={() => setConfirmDel(false)}>Cancelar</button>
                <button className="btn btn--danger" onClick={() => { setConfirmDel(false); onLogout(); }}>Apagar permanentemente</button>
              </div>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}

Object.assign(window, { ProfilePage });
